openapi: 3.0.0
info:
  title: OCR API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.0.1
servers:
  - url: http://192.168.1.57:8888
    description: Ocr server description, e.g. Main (production) server
paths:
  /ocr:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string


    post:
      summary: Return text from image
      description: get text
      requestBody:
        required: true
        content:
          application/json:
            schema: object
            properties:
            image_path:
            type: string
      responses:
        '201':
          description: uploaded
